### ISSUE TITLE
Issue in importing images from CSS. 

### ISSUE THREAD

**Issue by vigneshshanmugam** [boopathi/image-size-loader#7]
When we import images in CSS like this 

``` css
.bgImage {
    background-image: url('example.png');
    width: 200px;
    height: 200px;
}
```

Since the CSS will already be in webpack publicPath folder, the image request for example.png will be 

``` js
http://localhost:3000/public/public/example-f1df98cf.png
```

This happens because of this line https://github.com/boopathi/image-size-loader/blob/master/index.js#L18. We need to remove **webpack_public_path** on toString method to fix this. 

Check this #6
